version: "3"
services:

  db:
    container_name: cellscan_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${CELLSCAN_DB_PASS}
    healthcheck:
      test: mysqladmin ping -u${CELLSCAN_DB_USER} -p${CELLSCAN_DB_PASS}

  backup:
    container_name: cellscan_backup
    image: databack/mysql-backup:latest
    user: root
    volumes:
      - ${CELLSCAN_BACKUP_DIR}:/backups
    environment:
      DB_SERVER: db
      DB_DUMP_FREQ: ${CELLSCAN_DB_DUMP_FREQ}
      DB_USER: ${CELLSCAN_DB_USER}
      DB_PASS: ${CELLSCAN_DB_PASS}
      DB_DUMP_TARGET: /backups
      DB_DUMP_SAFECHARS: true
    depends_on:
      db:
        condition: service_healthy

  caddy:
    container_name: cellscan_caddy
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
      
  backend:
    container_name: cellscan_backend
    build: .
    environment:
      CELLSCAN_DB_DRIVER: ${CELLSCAN_DB_DRIVER}
      CELLSCAN_DB_USER: ${CELLSCAN_DB_USER}
      CELLSCAN_DB_PASS: ${CELLSCAN_DB_PASS}
      CELLSCAN_DB_HOST: ${CELLSCAN_DB_HOST}
      CELLSCAN_DB_PORT: ${CELLSCAN_DB_PORT}
      CELLSCAN_DB_DB: ${CELLSCAN_DB_DB}
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
