version: "3"
services:
  db:
    container_name: cellscan_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    healthcheck:
      test: mysqladmin ping -u${DB_USER} -p${DB_PASS}
  backup:
    container_name: cellscan_backup
    image: databack/mysql-backup:latest
    user: root
    volumes:
      - ${HOST_BACKUP_DIR}:/backups
    environment:
      DB_SERVER: db
      DB_DUMP_FREQ: 1440
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DUMP_TARGET: /backups
      DB_DUMP_SAFECHARS: true
    depends_on:
      db:
        condition: service_healthy
  backend:
    container_name: cellscan_backend
    build: .
    ports:
      - 8000:80
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      db:
        condition: service_healthy